package softwaredesign;

import softwaredesign.*;

import java.awt.*;
import javax.swing.*;


public class GUI extends javax.swing.JFrame {

<<<<<<< HEAD:src/main/java/softwaredesign/GUI.java
    int x = 0, y = 0;

    /*
     * Creates new form softwaredesign.GUI
=======
    int x=0,y=0;


    /**
     * Creates new form GUI
>>>>>>> main:src/main/java/GUI.java
     */
    public GUI() {
        initComponents();
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnRules = new javax.swing.JButton();
        btnRules2 = new javax.swing.JButton();
        btnMachine1 = new javax.swing.JButton();
        btnMachine2 = new javax.swing.JButton();
        btnMachine3 = new javax.swing.JButton();
        btnMachine4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        discardPile = new javax.swing.JButton();
        mainPile = new javax.swing.JButton();
        CB = new javax.swing.JComboBox<>();
        drawCardBtn = new javax.swing.JButton();
        endTurnBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRules.setBackground(new java.awt.Color(255, 255, 255));
        btnRules.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnRules.setText("General Rules");
        btnRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRulesActionPerformed(evt);
            }
        });

        btnRules2.setBackground(new java.awt.Color(255, 255, 255));
        btnRules2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnRules2.setText("Card Rules");
        btnRules2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRules2ActionPerformed(evt);
            }
        });

        btnMachine1.setBackground(new java.awt.Color(255, 255, 255));
        btnMachine1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnMachine1.setText("Machine 1");
        btnMachine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMachine1ActionPerformed(evt);
            }
        });

        btnMachine2.setBackground(new java.awt.Color(255, 255, 255));
        btnMachine2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnMachine2.setText("Machine 2");
        btnMachine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMachine2ActionPerformed(evt);
            }
        });

        btnMachine3.setBackground(new java.awt.Color(255, 255, 255));
        btnMachine3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnMachine3.setText("Machine 3");
        btnMachine3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMachine3ActionPerformed(evt);
            }
        });

        btnMachine4.setBackground(new java.awt.Color(255, 255, 255));
        btnMachine4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnMachine4.setText("Machine 4");
        btnMachine4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMachine4ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        discardPile.setText("Discard");
        discardPile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardPileActionPerformed(evt);
            }
        });

        mainPile.setText("Main");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(330, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(mainPile, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(discardPile, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(discardPile, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mainPile, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(308, Short.MAX_VALUE))
        );



        CB.setMaximumRowCount(20);
<<<<<<< HEAD:src/main/java/softwaredesign/GUI.java
        CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Card 1", "Card 2", "Card 3", "Card 4", "Card 5", "Card 6", "Card 7", "Card 8", "Card 9", "Card 10", "Card 11", "Card 12", "Card 13", "Card 14", "Card 15", "Card 16", "Card 17", "Card 18", "Card 19", "Card 20"}));
=======
        CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"TacoCat", "Cattermelon", "BeardCat", "RainbowRalphingCat", "HairyPotatoCat", "SeeFuture",
                "Shuffle", "Favor", "Skip", "Attack", "Nope", "Defuse", "ExplodingKitten"}));
>>>>>>> main:src/main/java/GUI.java
        CB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBMouseClicked(evt);
            }
        });
        CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBActionPerformed(evt);
            }
        });

        drawCardBtn.setText("Play Card");
        drawCardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawCardBtnActionPerformed(evt);
            }
        });

        endTurnBtn.setBackground(new java.awt.Color(255, 255, 255));
        endTurnBtn.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        endTurnBtn.setText("End Turn");
        endTurnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTurnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnMachine1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnMachine2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnMachine3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnMachine4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(endTurnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(btnRules)
                                .addComponent(btnRules2)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(CB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(drawCardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnRules, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnRules2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnMachine1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnMachine2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnMachine3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnMachine4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(endTurnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(CB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(drawCardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private static void btnRulesActionPerformed(java.awt.event.ActionEvent evt) {

        JFrame f = new JFrame(); //creates jframe f
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize(); //this is your screen size
        f.setUndecorated(true); //removes the surrounding border
        ImageIcon image = new ImageIcon("src/main/java/EnglishRules-1.png"); //imports the image
        JLabel lbl = new JLabel(image); //puts the image into a jlabel
        f.getContentPane().add(lbl); //puts label inside the jframe
        f.setSize(image.getIconWidth(), image.getIconHeight()); //gets h and w of image and sets jframe to the size
        int x = (screenSize.width - f.getSize().width)/4; //These two lines are the dimensions
        int y = (screenSize.height - f.getSize().height)/4;//of the center of the screen
        f.setLocation(x, y); //sets the location of the jframe
        f.setVisible(true); //makes the jframe visible
    }
    private static void btnRules2ActionPerformed(java.awt.event.ActionEvent evt) {

        JFrame f = new JFrame(); //creates jframe f
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize(); //this is your screen size
        f.setUndecorated(true); //removes the surrounding border
        ImageIcon image2 = new ImageIcon("src/main/java/EnglishRules-2.png"); //imports the image
        JLabel lbl2 = new JLabel(image2); //puts the image into a jlabel
        f.getContentPane().add(lbl2); //puts label inside the jframe
        f.setSize(image2.getIconWidth(), image2.getIconHeight()); //gets h and w of image and sets jframe to the size
        int x = (screenSize.width - f.getSize().width)/4; //These two lines are the dimensions
        int y = (screenSize.height - f.getSize().height)/4;//of the center of the screen
        f.setLocation(x, y); //sets the location of the jframe
        f.setVisible(true); //makes the jframe visible
    }


    private void btnMachine1ActionPerformed(java.awt.event.ActionEvent evt) {
        // add actions here:
    }

    private void btnMachine2ActionPerformed(java.awt.event.ActionEvent evt) {
        // add actions here:
    }

    private void btnMachine3ActionPerformed(java.awt.event.ActionEvent evt) {
        // add actions here:
    }

    private void btnMachine4ActionPerformed(java.awt.event.ActionEvent evt) {
        // add actions here:
    }

    private void addCardInList(String name) {
        CB.addItem(name);
    }

    private void CBActionPerformed(java.awt.event.ActionEvent evt) {


    }

    private void discardPileActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add discard pile handling code here:
    }

    private void CBMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add handling code here:

    }

    private void drawCardBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add handling code here:
        try {
            JButton card = new JButton(CB.getSelectedItem().toString());
            card.setBounds(x, y, mainPile.getWidth(), mainPile.getHeight());
            card.setVisible(true);
            jPanel1.add(card);
            jPanel1.revalidate();
            jPanel1.repaint();

            CB.removeItemAt(CB.getSelectedIndex());
        } catch (Exception e) {
        }
        x += 20;
        y += 20;
    }

    private void endTurnBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add end turn handling code here:
    }

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    public void createlabel() {
        Label l = new Label();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> CB;
    private javax.swing.JButton btnMachine1;
    private javax.swing.JButton btnMachine2;
    private javax.swing.JButton btnMachine3;
    private javax.swing.JButton btnMachine4;
    private javax.swing.JButton btnRules;
    private javax.swing.JButton btnRules2;
    private javax.swing.JButton discardPile;
    private javax.swing.JButton drawCardBtn;
    private javax.swing.JButton endTurnBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainPile;
    // End of variables declaration                   
}
